# mindsensors.com PiStorms

pistorms-objs := pistorms_core.o pistorms_battery.o pistorms_input.o pistorms_leds.o \
	pistorms_ports_in.o pistorms_ports_out.o pistorms_board_info.o
obj-$(CONFIG_PISTORMS)	+= pistorms.o
