obj-$(CONFIG_LMS2012_COMPAT)	+= d_analog.o
obj-$(CONFIG_LMS2012_COMPAT)	+= d_iic.o
obj-$(CONFIG_LMS2012_COMPAT)	+= d_pwm.o
obj-$(CONFIG_LMS2012_COMPAT)	+= d_uart.o
obj-$(CONFIG_LMS2012_COMPAT)	+= lms2012_compat.o
