
# hack to use platform-specific timer driver
KBUILD_CFLAGS += -Iarch/arm/plat-omap/include

obj-$(CONFIG_LMS2012_COMPAT)	+= d_analog.o
obj-$(CONFIG_LMS2012_COMPAT)	+= d_pwm.o
obj-$(CONFIG_LMS2012_COMPAT)	+= d_uart.o
obj-$(CONFIG_LMS2012_COMPAT)	+= lms2012_compat.o
