# Dexter Industries BrickPi

brickpi-objs := brickpi_serdev.o brickpi_ports_in.o brickpi_ports_out.o
obj-$(CONFIG_BRICKPI)	+= brickpi.o
obj-$(CONFIG_BRICKPI)	+= brickpi_i2c_sensor.o

obj-$(CONFIG_BRICKPI_BATTERY)	+= brickpi_battery.o
