# Sensor class
obj-$(CONFIG_LEGOEV3_MSENSORS)		+= lego_sensor_class.o

# Analog Sensors
ev3_analog_sensor-objs := ev3_analog_sensor_core.o ev3_analog_sensor_defs.o
obj-$(CONFIG_EV3_ANALOG_SENSORS)	+= ev3_analog_sensor.o

# UART Sensors
ev3_uart_sensor-objs := ev3_uart_sensor_core.o ev3_uart_sensor_defs.o
obj-$(CONFIG_EV3_UART_SENSORS)		+= ev3_uart_sensor.o
