# EV3

obj-$(CONFIG_LEGOEV3_ANALOG)		+= legoev3_analog.o
obj-$(CONFIG_BATTERY_LEGOEV3)		+= legoev3_battery.o
obj-$(CONFIG_LEGOEV3_BLUETOOTH)		+= legoev3_bluetooth.o
legoev3_ports-objs := legoev3_ports_core.o ev3_input_port.o ev3_output_port.o
obj-$(CONFIG_LEGOEV3_DEV_PORTS)		+= legoev3_ports.o
