# Motor classes
obj-$(CONFIG_LEGO_TACHO_MOTORS)	+= tacho_motor_class.o
obj-$(CONFIG_LEGO_SERVO_MOTORS)	+= servo_motor_class.o
obj-$(CONFIG_LEGO_DC_MOTORS)	+= dc_motor_class.o

# Motors
obj-$(CONFIG_LEGO_DC_MOTORS)	+= rcx_motor.o
obj-$(CONFIG_LEGO_DC_MOTORS)	+= rcx_led.o
