# Motor classes
tacho_motor-objs := tacho_motor_class.o tacho_motor_helper.o
obj-$(CONFIG_LEGO_TACHO_MOTORS)	+= tacho_motor.o
obj-$(CONFIG_LEGO_SERVO_MOTORS)	+= servo_motor_class.o
obj-$(CONFIG_LEGO_DC_MOTORS)	+= dc_motor_class.o

# Motors
ev3_motor-objs := ev3_motor_core.o ev3_motor_defs.o
obj-$(CONFIG_LEGO_TACHO_MOTORS)	+= ev3_motor.o
obj-$(CONFIG_LEGO_DC_MOTORS)	+= rcx_motor.o
obj-$(CONFIG_LEGO_DC_MOTORS)	+= rcx_led.o
