# Motor classes
obj-$(CONFIG_LEGOEV3_MOTORS)		+= tacho_motor_class.o
obj-$(CONFIG_LEGOEV3_SERVO_MOTORS)	+= servo_motor_class.o
obj-$(CONFIG_LEGOEV3_DC_MOTORS)		+= dc_motor_class.o

# Motors
obj-$(CONFIG_LEGOEV3_TACHO_MOTORS)	+= ev3_tacho_motor.o
obj-$(CONFIG_LEGOEV3_DC_MOTORS)		+= rcx_motor.o
obj-$(CONFIG_LEGOEV3_DC_MOTORS)		+= rcx_led.o
