# Dexter Industries BrickPi3

brickpi3-objs := brickpi3_i2c.o brickpi3_iio.o brickpi3_leds.o \
		 brickpi3_ports_in.o brickpi3_ports_out.o brickpi3_spi.o \
		 brickpi3_board_info.o
obj-$(CONFIG_BRICKPI3)	+= brickpi3.o
obj-$(CONFIG_BRICKPI3)	+= brickpi3_battery.o
